//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomToolbox.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("onedrive.live.com;gothuedutw-my.sharepoint.com;twitcasting.tv;drive.google.com;")]
        public string NetPlaylistUnsupportedDomains {
            get {
                return ((string)(this["NetPlaylistUnsupportedDomains"]));
            }
            set {
                this["NetPlaylistUnsupportedDomains"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MpvNetLibVolume {
            get {
                return ((int)(this["MpvNetLibVolume"]));
            }
            set {
                this["MpvNetLibVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MpvNetLibPlaybackSpeedIndex {
            get {
                return ((int)(this["MpvNetLibPlaybackSpeedIndex"]));
            }
            set {
                this["MpvNetLibPlaybackSpeedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MpvNetLibNoVideo {
            get {
                return ((bool)(this["MpvNetLibNoVideo"]));
            }
            set {
                this["MpvNetLibNoVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MpvNetLibYTQualityIndex {
            get {
                return ((int)(this["MpvNetLibYTQualityIndex"]));
            }
            set {
                this["MpvNetLibYTQualityIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double PlaylistAppendSeconds {
            get {
                return ((double)(this["PlaylistAppendSeconds"]));
            }
            set {
                this["PlaylistAppendSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime YtDlpCheckTime {
            get {
                return ((global::System.DateTime)(this["YtDlpCheckTime"]));
            }
            set {
                this["YtDlpCheckTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YtDlpCookieFromBrowser {
            get {
                return ((bool)(this["YtDlpCookieFromBrowser"]));
            }
            set {
                this["YtDlpCookieFromBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chrome")]
        public string YtDlpBrowserName {
            get {
                return ((string)(this["YtDlpBrowserName"]));
            }
            set {
                this["YtDlpBrowserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string YtDlpBrowserProfilePath {
            get {
                return ((string)(this["YtDlpBrowserProfilePath"]));
            }
            set {
                this["YtDlpBrowserProfilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YtDlpUseAria2 {
            get {
                return ((bool)(this["YtDlpUseAria2"]));
            }
            set {
                this["YtDlpUseAria2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppLangCode {
            get {
                return ((string)(this["AppLangCode"]));
            }
            set {
                this["AppLangCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AppTheme {
            get {
                return ((string)(this["AppTheme"]));
            }
            set {
                this["AppTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NetPlaylistAutoLyric {
            get {
                return ((bool)(this["NetPlaylistAutoLyric"]));
            }
            set {
                this["NetPlaylistAutoLyric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MpvNetLibLogVerbose {
            get {
                return ((bool)(this["MpvNetLibLogVerbose"]));
            }
            set {
                this["MpvNetLibLogVerbose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscordRichPresence {
            get {
                return ((bool)(this["DiscordRichPresence"]));
            }
            set {
                this["DiscordRichPresence"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1039536928221036576")]
        public string DiscrodApplicationID {
            get {
                return ((string)(this["DiscrodApplicationID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DiscrodMaxConnectionFailedCount {
            get {
                return ((int)(this["DiscrodMaxConnectionFailedCount"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) " +
            "Chrome/108.0.0.0 Safari/537.36")]
        public string UserAgent {
            get {
                return ((string)(this["UserAgent"]));
            }
            set {
                this["UserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2*")]
        public global::System.Windows.GridLength RDGContentRow1Height {
            get {
                return ((global::System.Windows.GridLength)(this["RDGContentRow1Height"]));
            }
            set {
                this["RDGContentRow1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public global::System.Windows.GridLength RDGContentRow3Height {
            get {
                return ((global::System.Windows.GridLength)(this["RDGContentRow3Height"]));
            }
            set {
                this["RDGContentRow3Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public global::System.Windows.GridLength CDGContentCol1Width {
            get {
                return ((global::System.Windows.GridLength)(this["CDGContentCol1Width"]));
            }
            set {
                this["CDGContentCol1Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public global::System.Windows.GridLength CDGContentCol3Width {
            get {
                return ((global::System.Windows.GridLength)(this["CDGContentCol3Width"]));
            }
            set {
                this["CDGContentCol3Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public global::System.Windows.GridLength RDTIClipPlayerRow1Height {
            get {
                return ((global::System.Windows.GridLength)(this["RDTIClipPlayerRow1Height"]));
            }
            set {
                this["RDTIClipPlayerRow1Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public global::System.Windows.GridLength RDTIClipPlayerRow3Height {
            get {
                return ((global::System.Windows.GridLength)(this["RDTIClipPlayerRow3Height"]));
            }
            set {
                this["RDTIClipPlayerRow3Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenCCS2TWP {
            get {
                return ((bool)(this["OpenCCS2TWP"]));
            }
            set {
                this["OpenCCS2TWP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YtDlpEmbedMetadata {
            get {
                return ((bool)(this["YtDlpEmbedMetadata"]));
            }
            set {
                this["YtDlpEmbedMetadata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YtDlpLiveFromStart {
            get {
                return ((bool)(this["YtDlpLiveFromStart"]));
            }
            set {
                this["YtDlpLiveFromStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YtDlpWaitForVideo {
            get {
                return ((bool)(this["YtDlpWaitForVideo"]));
            }
            set {
                this["YtDlpWaitForVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool YtDlpSplitChapters {
            get {
                return ((bool)(this["YtDlpSplitChapters"]));
            }
            set {
                this["YtDlpSplitChapters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b/bv*+ba")]
        public string YtDlpFormat {
            get {
                return ((string)(this["YtDlpFormat"]));
            }
            set {
                this["YtDlpFormat"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int YtDlpWaitForVideoSeconds {
            get {
                return ((int)(this["YtDlpWaitForVideoSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b/bv*+ba")]
        public string YtDlpDefaultFormat {
            get {
                return ((string)(this["YtDlpDefaultFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int YtDlpConcurrentFragments {
            get {
                return ((int)(this["YtDlpConcurrentFragments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("all,-live_chat")]
        public string YtDlpSubLangs {
            get {
                return ((string)(this["YtDlpSubLangs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool YtDlpEmbedSubs {
            get {
                return ((bool)(this["YtDlpEmbedSubs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FFmpegHardwareAccelerationType {
            get {
                return ((string)(this["FFmpegHardwareAccelerationType"]));
            }
            set {
                this["FFmpegHardwareAccelerationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FFmpegGpuDeviceIndex {
            get {
                return ((int)(this["FFmpegGpuDeviceIndex"]));
            }
            set {
                this["FFmpegGpuDeviceIndex"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Intel")]
        public string FFmpegDefaultHardwareAccelerationType {
            get {
                return ((string)(this["FFmpegDefaultHardwareAccelerationType"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FFmpegEnableHardwareAcceleration {
            get {
                return ((bool)(this["FFmpegEnableHardwareAcceleration"]));
            }
            set {
                this["FFmpegEnableHardwareAcceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FFmpegApplyFontSetting {
            get {
                return ((bool)(this["FFmpegApplyFontSetting"]));
            }
            set {
                this["FFmpegApplyFontSetting"] = value;
            }
        }
    }
}
